### ISSUE TITLE
setVolume is not a function

### ISSUE THREAD

**Issue by drscottlobo** [danigb/smplr#19]
Hi @danigb, hope all goes well! 

Looks like the Soundfont player object is giving the following error: player.setVolume() is not a function. 

I had a look at the object in the console and it looks like that function is currently in player.output, so player.output.setVolume() works. Is that the intended functionality, or should the function be moved? 

I still want to have a way to buy you a coffee! This library is saving me so much time!

**Comment by danigb** [comment]
I'm glad this is useful for you @drscottlobo 👍  And you're right, the function is in `player.output`, we need to fix the documentation (PRs welcomed)

I don't accept donations by now, but thanks ☕

**Comment by drscottlobo** [comment]
Submitted a PR for the update to the docs :)
