### ISSUE TITLE
Error: "Relative module specifiers must start with “./”, “../” or “/”.`"

### ISSUE THREAD

**Issue by msh75** [danigb/smplr#35]
Hi,
I'm getting this error when trying  to make a simple sound :
`Uncaught TypeError: The specifier “smplr” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.`
The code I run -after installing using 'npm i smplr' is like this:
```
<script type="module">
import { Soundfont } from "smplr";
const context = new AudioContext();
const marimba = new Soundfont(context, { instrument: "marimba" });
marimba.start({ note: 60, velocity: 80 });
</script>
```

**Comment by danigb** [comment]
There are two issues with your code:
1. npm packages needs a url to be retrieved 
2. you need to play audio after a user interaction

This code will work (tested on [codepen](https://codepen.io/pen/)). In this example I used unpkg.com, but any other service could work:

```html
<html>
  <script type="module">
    import { Soundfont } from "https://unpkg.com/smplr@0.10.0/dist/index.mjs"; // needs to be a url
    const context = new AudioContext(); // create the audio context
    const marimba = new Soundfont(context, { instrument: "marimba" }); // create the player
    document.getElementById("btn").onclick = async () => {
      context.resume(); // enable audio context after a user interaction
      marimba.start({ note: 60, velocity: 80 }); // play the note    
    }
</script>
  <body>
    <button id="btn">play</button>
  </body>
</html>
```

Feel free to reopen if you still have problems.
