### ISSUE TITLE
Can't get soundfont-player to work on Mac (Safari or Chrome)

### ISSUE THREAD

**Issue by AlanPaine** [danigb/smplr#4]
Mode of use：

import { Soundfont } from "smplr";

const context = new AudioContext();
const marimba = new Soundfont(context, { instrument: "marimba" });
marimba.start({ note: 60, velocity: 80 });

I can't find the percussion, and I can't find a way to set the volume function。 https://gleitz.github.io/midi-js-soundfonts/MusyngKite/percussion-ogg.js

**Comment by danigb** [comment]
It should be fixed now in latest version (0.4.3). See here: https://jsfiddle.net/k4Lodqmc/1/

Thanks for reporting
