### ISSUE TITLE
Playing notes does extra logging in the console

### ISSUE THREAD

**Issue by hylu-dev** [danigb/smplr#40]
Hi, with the recent updates, I'm seeing some new logging that's filling up the console whenever a note is played.

On note start it logs: `Object { sample: {…} }`
On note end it logs `">>>> END undefined`

Borrowing a recent user's codepen, you can see the console fill up as notes are played https://codesandbox.io/s/young-monad-forked-lw8pyj?file=/src/index.js

**Comment by danigb** [comment]
Yes, weird, because there's no console.log in the code base... I think I've accidentally publish a previous version. I'll fix it. Thanks for the codepen 👍

**Comment by danigb** [comment]
It is fixed in 0.10.2
