### ISSUE TITLE
setVolume and reverb effect no longer working.

### ISSUE THREAD

**Issue by hylu-dev** [danigb/smplr#42]
Hi, been loving package and appreciate the quick responses.

I think this issue was here on recent prior versions but only just tested now.

Setting the volume to 0 and max reverb results in the piano still outputting sound as well as no reverb. Updating the volume or reverb with sendEffect thereafter has no effect either. I believe velocity still works as intended though.

https://codesandbox.io/s/young-monad-forked-lw8pyj?file=/src/index.js
- Not sure if it's a codepen issue or part of the bug, refresh the codepen to ensure it plays

**Comment by drscottlobo** [comment]
Same here, player.output.setVolume() no longer has any effect, I don't think it's a codepen issue.

**Comment by drscottlobo** [comment]
I tried to a work-around by setting velocity on each note, which has some effect on the overall volume, but a new bug perhaps: 0 velocity note still plays back sound.

**Comment by danigb** [comment]
Sorry for the inconvenience. Fixed in 0.10.3

**Comment by hylu-dev** [comment]
Looks good now. Thank you!
