### ISSUE TITLE
Version 0.11.0 - onStart does not fire when added to player.start({})

### ISSUE THREAD

**Issue by drscottlobo** [danigb/smplr#45]
Hi there! I'm so excited that you have added an onStart to smplr! I've just tested it as follows. onEnded fires after 1 second, but onStart doesn't seem to fire. (This is using the Soundfont player - I think the onStart might just be missing from that class?)

`
player.start({
			note: "C4",
			duration: 1,
			onEnded: () => {
				console.log("I ended!");
			},
			onStart: () => {
				console.log("started!");
			},
		});`

**Comment by hylu-dev** [comment]
Fix looks good! Using it now in my own project with the soundfont player. Really happy with the new callback.

**Comment by drscottlobo** [comment]
Yep! Working on my end, thanks!

**Comment by danigb** [comment]
Thanks for checking!
