### ISSUE TITLE
Providing frequency for playback instead of notename/noteNumber

### ISSUE THREAD

**Issue by alexshenker** [danigb/smplr#72]
How fisable is it to provide frequencies for playback for `soundfont.start`?

I understand there is a 'detune' option - I couldn't quite get that to work. but regardless,
I'm interested in providing specific frequencies for the instrument to playback. 
Would that be complex to implement?

**Comment by danigb** [comment]
Hi, this is a sampler based instrument, so you can only pitch the sounds by altering the speed (aka: detune). The only option is to calculate the detune for each note. The idea is to convert a frequency to midi (with decimals) and then select the integer part to choose the note and the float part to detune. 

Given this freqToMidi function:
```
export function freqToMidi(freq: number): number {
  const v = (12 * (Math.log(freq) - L440)) / L2 + 69;
  return Math.round(v * 100) / 100;
}
```

If you want to play a sample a 360Hz then:
```
freqToMidi(360); => 65.53
instrument.start({ note: 65, detune: 53 });
```
Hope it helps

**Comment by alexshenker** [comment]
> Hi, this is a sampler based instrument, so you can only pitch the sounds by altering the speed (aka: detune). The only option is to calculate the detune for each note. The idea is to convert a frequency to midi (with decimals) and then select the integer part to choose the note and the float part to detune.
> 
> Given this freqToMidi function (taken from [tonal](github.com/tonaljs)):
> 
> ```js
> function freqToMidi(freq: number): number {
>   const v = (12 * (Math.log(freq) - Math.log(440)) / Math.log(2) + 69;
>   return Math.round(v * 100) / 100;
> }
> ```
> 
> If you want to play a sample a 360Hz then:
> 
> ```js
> freqToMidi(360); => 65.53
> instrument.start({ note: 65, detune: 53 });
> ```
> 
> Hope it helps

This was helpful, thank you

**Comment by alexshenker** [comment]
@danigb I do have a followup question,
Playback works in terms of instrument.start. Any known reason why the detune property wouldn't affect the tone?
I tried it when first setting up the instrument via `new Soundfont`, and I tried changing it when calling `instrument.start()`, however the pitch remains the same.
Any ideas?

Thank you

**Comment by danigb** [comment]
It was a bug. Should be fixed in latest version.

**Comment by alexshenker** [comment]
> It was a bug. Should be fixed in latest version.

@danigb , It is fixed when using it in `instrument.start({ detune: ...})`, however, using detune in 
```ts
new Soundfont(audioCtx, { detune: ...})
```
Doesn't have an effect it seems.
