### ISSUE TITLE
[BUG] Terrible loops on some instruments

### ISSUE THREAD

**Issue by spessasus** [danigb/smplr#90]
## The issue
Some instruments have terribly set up loops, that cause a lot of clicking when the note is held down.
## Instruments I've found issues with (tested MusyngKite):
 - contrabass (the worst one)
 - trumpet (might be even worse than contrabass)
 - bagpipe
 - applause
 - bassoon
 - church organ ( clicks after every 3 seconds or so)
 - cello
 - drawbar organ
 - english horn
 - harmonica
 - piccolo
 - viola
 - violin
## How to reproduce
1. Go to [https://danigb.github.io/smplr/](https://danigb.github.io/smplr/)
2. Load the MusyngKite soundfont
3. select any instrument of the listed ones (contrabass for example)
4. Hold down a key
5. Hear clicks with loops
### Tested on
Firefox 126.0.1 (Arch Linux)
Chromium 125.0.6422.141 (Arch Linux)
### Expected result
The instruments should play fine when the key is held down.

**Comment by danigb** [comment]
Yes, I'm aware of those problems. If you really need good looping, you probably need to use the sf2 files directly: https://github.com/danigb/smplr?tab=readme-ov-file#soundfont2sampler

**Comment by danigb** [comment]
Closing this since sample precision loops are handled by Soundfont2 sampler. Please feel free to reopen if issue persist.
