### ISSUE TITLE
Musyng sf2 does not sound correct

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [danigb/smplr#93]
I wanted to use the looping in the Musyng soundfont so I took the original and split it by patch using Polyphone (so users don't have to download 1gb at the start), however it seems that some of the patches don't sound correctly. For example the clavinet patch jumps in pitch at every octave, the honkytonk piano patch sounds just very off and some other issues. I'm not sure what the cause is, either the soundfont itself, soundfont2 or smplr. It seems like the soundfonts worked in other players like the FlStudio soundfont player.

Could I ask for help in testing? My .sf2 files can be found here and are in GM order: https://github.com/henrikvilhelmberglund/keyboard/tree/main/static/sf2/musyng

**Comment by danigb** [comment]
Not sure what are you trying to do, but if you want to use Musyng I'd recommend to use Soundfont player directly (that loads only the required mp3 files)

BTW: I can't access the sf2 file to test. I'd need a public url (something like https://keyboard-gamma.vercel.app/sf2/musing/file.sf2)

**Comment by danigb** [comment]
Updated: added the ability to upload a custom sf2 from a public url in the Soundfont2 example

See: https://github.com/danigb/smplr/pull/94

**Comment by henrikvilhelmberglund** [comment]
I have my own code that uses the new soundfont2 player. I used the mp3 player before but looping is broken so I wanted to use the real soundfonts with actual loop points.

Thanks for the custom URL feature! Here is a real URL to the sf2 now: `https://keyboard.henrikvilhelmberglund.com/sf2/musyng/007.sf2`

It can also be used in https://keyboard.henrikvilhelmberglund.com/ (semi broken atm)

It seems like I get the same issue on the demo site, I'll see if another soundfont has the same issue but I suspect the soundfont itself is non standard.

**Comment by henrikvilhelmberglund** [comment]
It seems like `soundfont2` doesn't use the "Root key" (not sample root key) value in an instrument which causes the notes to get offset. I'm not sure how to fix this so I think I'll just make a custom soundbank bank with sf2s I have confirmed work corectly.

An example for anyone interested is the Vibraphone instrument in Musyng which has an "F" sample on key 63 which is not offset correctly (and all notes to the right basically): 
![image](https://github.com/user-attachments/assets/55c32629-5e2a-4dff-9468-c3fe0828182e)

Anyway it's possible to get around it so I'll close this.

**Comment by henrikvilhelmberglund** [comment]
I tested the file in https://github.com/spessasus/SpessaSynth and it worked perfectly in there, it seems like that library has a more complete sf2 (and sf3!) parsing implementation. Maybe this could work for `smplr` as well?

**Comment by danigb** [comment]
Hey, SpessaSynth looks awesome. Is there any reason not to use it instead of smplr? (genuine curiousity)

**Comment by henrikvilhelmberglund** [comment]
It seems pretty great indeed, I'm going to use both, SpessaSynth for soundfonts and smplr for the other sample based instruments.
