### ISSUE TITLE
Wrong notes playing with MIDI Messages and Wrong Number of Instruments Loaded

### ISSUE THREAD

**Issue by jshamble** [danigb/smplr#96]
Some loaded soundfonts (with Soundfont2Sampler) are playing the wrong notes when sent the correct midi messages.

For instance, [SGM-V2.01](https://archive.org/details/SGM-V2.01)

Plays very different and incorrectly mapped notes when trying to play a simple C Major scale (from C4 to C5) on the piano instrument, this happens on most instruments.

Also, it seems like some soundfonts like [maganda piano](https://www.polyphone.io/en/soundfonts/pianos/302-maganda-piano) load 4 different pianos, wheres a DAW like LMMS would only load one, it seems like there is possibly some incorrect or extra information/layers being loaded.

**Comment by danigb** [comment]
The goal of smplr is to provide easy to use instruments with no setup. Probably handling those big and complex sf2 files are out of scope. https://github.com/spessasus/SpessaSynth could be a good fit for you.
