### ISSUE TITLE
DrumMachine sample names

### ISSUE THREAD

**Issue by larscupec** [danigb/smplr#98]
Hi, I was checking out your library and must congratulate you for making it very easy and intuitive to use. But I've come across one small issue.

When using the `DrumMachine` it kept giving me a warning that some samples could not be found. The way I was using it was that I was giving it sample names as they are listed in the json file (such as this one [https://smpldsnds.github.io/drum-machines/Casio-RZ1/dm.json](url). But that doesn't work.

I think I may have found the reason why is that. There is a line in `drum-machine.ts` that replaces `'-'` characters with `'/'` in sample names. I don't know if it is the intended way of using the `DrumMachine` but when I changed the sample names in my code to use `'/'` instead of `'-'` it worked!

Again, nothing major, just thought it would be useful to state that somewhere in the `README`.
Thanks.

**Comment by jeffgord** [comment]
Wow, crazy world! I was also working with the drum machine stuff today, and was struggling to figure out why some of the drum machines weren't making sounds for certain samples. Your comment saved me!

Another thing that took me a while to figure out is that not all the drum machines in the smpldsnds drum machines repository are supported out of the box by smplr. The `getDrumMachineNames` lists the names of the ones that are supported.

**Comment by jeffgord** [comment]
I'm not the OP, but this looks good to me - I think the readme documentation will be especially helpful to others looking to use the drum machines. Thanks for the quick response!

**Comment by danigb** [comment]
Fixed by #99
